version: '3.8'

services:
  # Aplicacao Web Django
  appdjango:
    build:
      context: .
      args:
        PROJ_APP_NAME: ${DJANGO_APP_NAME}
    container_name: django
    env_file:
      - config/env/env_django
    volumes:
      - .:/opt/services/${DJANGO_APP_NAME}/src
    ports:
      - 8000:8000
    networks:
      - database_network
    depends_on:
      - postgresql
      
  # Bando de dados PostgreSQL
  postgresql:
    image: postgres:11
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - config/env/env_database
    volumes:
      - database_data:/var/lib/postgresql/data
    networks:
      - database_network
      
networks:
  database_network:
    driver: bridge
    
volumes:
  database_data: